### ISSUE TITLE
Getting Connection Errors - 5 Attempt to get blocked socket option

### ISSUE THREAD

**Issue by iamkhush** [agfor/braintree-python-appengine#1]
I used your app however, I am getting blocked socket errors when creating a token.

Here is my SO question with the stack trace. 
http://stackoverflow.com/questions/33037003/braintree-errors-with-gae-connection-errors-5-attempt-to-get-blocked-socket

**Comment by agfor** [comment]
I replied to your SO question, can you replace the `raise e` with `raise` and show the full backtrace from that?
